spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # 开发用localhost数据库
    driverClassName: org.postgresql.Driver

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG